version: '3.3'

services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_PASSWORD=p@ssw0rd
      - MYSQL_USER=me
      - MYSQL_DATABASE=seminar
